"""add precio column to productos

Revision ID: e640e981cb83
Revises: d5de788dadcd
Create Date: 2025-06-10 21:46:01.427431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e640e981cb83'
down_revision: Union[str, None] = 'd5de788dadcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('precio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'precio')
    # ### end Alembic commands ###
